version: '3.5'

services:
    server:
        env_file:
            - .env
        ports:
            - "8000:8000"
        image: "alexheld/hde-server:${SERVER_TAG}"
        build:
            context: server
            dockerfile: Dockerfile

    frontend:
        env_file:
            - .env
        image: "alexheld/hde-frontend:${FRONTEND_TAG}"
        ports:
            - "8080:80"
        build:
            labels:
                - maintainer=contact@alexheld.io
                - author=alex-held
            context: frontend
            dockerfile: Dockerfile
            args:
                GMAP_KEY: "${MAPS_API_KEY}"
