version: '3.5'

services:

    server:
        env_file:
            - prod.env
        ports:
            - "8000:8000"


    frontend:
        env_file:
            - prod.env
        ports:
            - "80:80"
