version: '3.5'


services:

    server:
        extends:
            file: docker-compose.yaml
            service: frontend
        env_file:
            - local.env

    frontend:
        env_file:
            - local.env
