version: '3.5'

services:

    server:
        env_file:
            - .env
            - prod.env
        ports:
            - "8000:8000"


    frontend:
        env_file:
            - .env
            - prod.env
        image: "alexheld/hde-frontend:${FRONTEND_TAG}"
        ports:
            - "80:80"
