version: '3.5'

services:

    server:
        extends:
            file: docker-compose.yaml
            service: server
        env_file:
            - prod.env
        ports:
            - "8000:8000"


    frontend:
        extends:
            file: docker-compose.yaml
            service: frontend
        env_file:
            - prod.env
        ports:
            - "80:80"
