version: '3.5'

services:
  backend:
    ports:
      - "8000:8000"
    image: alexheld/hde-backend
    build:
      context: server
      dockerfile: Multistage.Dockerfile

  server:
    container_name: "hde-server"
    ports:
    - "8015:8000"
    image: alexheld/hde-backend
    
    
  frontend:
    image: alex-held/hde-frontend
    build:
      context: .
      dockerfile: frontend/Dockerfile
